apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_HOST: bXlzcWxkYg==
  MYSQL_USER: a2V0YW4=
  MYSQL_PASSWORD: a2V0YW4=
  MYSQL_DATABASE: bmFtZQ==
  MYSQL_ROOT_PASSWORD: a2V0YW5w
